---
title: "..."
author: "..."
date: ".../.../..."
output: html_document
---

<!-- Ce document doit être cohérent et lisible dans sa version compilée (html). Assurez vous qu'il est bien compilable. -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
SciViews::R
library(pastecs)
source("../R/functions.R") # SciViews functions for CAH
```

# Introduction

<!-- Proposez une courte introduction de 4-5 phrases sur le jeu de données marphy du package pastecs. Cette introduction doit permettre de comprendre le document sans avoir besoin de lire un autre fichier. -->

# Analyses

```{r}
marphy <- read("marphy", package = "pastecs")
```

<!-- Proposez un tableau et deux graphiques pour explorer ce nouveau tableau de données. Décrivez votre tableau et vos graphiques en maximum 3 phrases. -->

```{r tab}

```

```{r plot1}

```

```{r plot2}

```

<!-- Proposez entre 4 et 6 dendrogrammes. Vous avez la possibilité de travailler
- sur la standardisation des données
- sur le choix de l'indice de distance
- sur le choix de la méthode de lien employée pour réaliser le dendrogramme 
- sur les regroupements en coupant l'arbre à la hauteur souhaitée.

Chaque stratégie employée pour réaliser vos dendrogrammes doit être explicitée. La description de votre dendrogramme doit permettre de comprendre les choix que vous avez pris.

Vos descriptions ne doivent pas dépasser 5-7 phrases. -->

```{r dendro1}

```

```{r dendro2}

```

```{r dendro3}

```

```{r dendro4}

```

```{r dendro5}

```

```{r dendro6}

```

# Conclusion

<!-- Terminez ce travail par une brève conclusion en répondant aux deux questions suivantes :

- Quel est votre meilleur dendrogramme ?
- Avez vous pu retrouver les 6 zones indiquées dans la page d'aide ? -->
